fix(docs): tell user how to deal with KeyErrors in old configs
kreshuklab/plant-seg pull request #277
Opened 2024-06-07 14:14 UTC by qin-yu

Try to improve error message for users to deal with `KeyError` introduced by upgrade.

Maybe we can also just delete the folders for them? @lorenzocerrone

2024-06-08 00:50 UTC, qin-yu commented
I've updated the installation documentation to address the `KeyError`, and I've also separated the macOS installation guide to potentially fix #273. Although I don't have access to an M-chip Mac for testing tonight, I followed the instructions from this PyTorch page and will verify it later. Feel free to test it if you have time.

![image](https://github.com/kreshuklab/plant-seg/assets/17722010/5a91f428-fb5d-4f8e-a06f-37ae864403b1)

2024-06-09 12:51 UTC, lorenzocerrone commented
Check #276 before merging the new docs. The python version needs to be pinned on Mac.

2024-06-09 12:54 UTC, lorenzocerrone commented on docs/chapters/getting_started/installation.md
> +        mamba create -n plant-seg -c pytorch -c conda-forge pytorch::pytorch pyqt plant-seg --no-channel-priority
python=3.11 #276

2024-06-09 12:56 UTC, lorenzocerrone commented on plantseg/run_plantseg.py
> +    except KeyError:
looks good

2024-06-09 12:57 UTC, lorenzocerrone requested changes
please @qin-yu pin the python version in the docs. Besides that looks great, you can merge!

2024-06-09 23:09 UTC, merged